### ISSUE TITLE
NoClassDefFoundError when running application

### ISSUE THREAD

**Issue by claudineigomes** [atende/audit-view#22]
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/core/env/Environment
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:123)
Caused by: java.lang.ClassNotFoundException: org.springframework.core.env.Environment
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

@giovannicandido

**Comment by claudineigomes** [comment]
after update Idea, this error disappeared

**Comment by giovannicandido** [comment]
ok
